### PR TITLE
Binary map

### PR DESCRIPTION
**Pull request by costashatz**
This pull request adds binary map stats and fixes one very small compilation issue (in the no parallel version of cvt_map_elites; also puts some more elaborate pre-processor labels)..

### CODE REVIEW

**Comment by costashatz** [comment]
@vassilisvas any comments? How does it look to you?

**Comment by vassilisvas** [comment]
Looks ok to me

**Comment by vassilisvas** [comment]
Merged

**Comment by costashatz** [comment]
Thanks!

**Pull request merged**
